version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "Hello"
      - run: curl http://checkip.amazonaws.com
      - run: sleep 80
      - run: echo "Adding comit 2021"
      - run: echo "new pr?"
