version: 2.1
jobs:
  build:
    machine: true
    #docker:
    #  - image: cimg/base:current
    #resource_class: small
    steps:
      - checkout
      - run: echo "Hello"
      - run: curl http://checkip.amazonaws.com
      - run: sleep 10
