version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: Retrive logs
          command: journalctl -f --no-pager
          background: true
      - run:
          name: Say Hello
          command: |
           echo "Hello"
           sleep 60

